"""Aggiunta colonna vm_id in VMRequest

Revision ID: 3b9acc1bb28d
Revises: 2fadc7bc291c
Create Date: 2025-12-23 09:43:27.087633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9acc1bb28d'
down_revision = '2fadc7bc291c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_config', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('vm_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vm_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_request', schema=None) as batch_op:
        batch_op.drop_column('vm_id')

    with op.batch_alter_table('vm_config', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
