"""Rimossa colonna cetegory da tabella VMConfig

Revision ID: e92dd8750d63
Revises: 3b9acc1bb28d
Create Date: 2025-12-23 16:46:51.214696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92dd8750d63'
down_revision = '3b9acc1bb28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_config', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
